data:
  data_dir: /Users/g6714/Projects/dnc/data/tasks_1-20_v1-2/en-10k
  cache_dir: /Users/g6714/Projects/dnc/cache
dataset:
  name: single-supporting-fact
  train:
    data_file: qa1_single-supporting-fact_train.txt
    train_cache_file: train.dat
    label_cache_file: train_labels.dat
  test:
    data_file: qa1_single-supporting-fact_test.txt
    test_cache_file: test.dat
    label_cache_file: test_labels.dat
model:
  name: dnc
  N: 256
  W: 64
  R: 2
  n_hidden: 512
  batch_size: 1
  disable_memory: False
  summary_dir:
  checkpoint_file:
  optimizer: Adagrad
  learning_rate: 0.001
  clip_gradients: 10.0
  data_dir: './dat'
